### ISSUE TITLE
Use @EnableWebSecurity instead of deprected @EnableWebMvcSecurity.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-guides/gs-authenticating-ldap#10]
The example currently uses @EnableWebMvcSecurity which is deprecated.
It should be replaced with @EnableWebSecurity.

**Comment by dsyer** [comment]
I think it's only deprecated in Spring Security 4.0? So we should wait till we upgrade.

**Comment by gregturn** [comment]
@dsyer The guides are now on Spring Boot 1.3.1.RELEASE. I presume that means we are now on Spring Security 4?

**Comment by chaitanyathengdi** [comment]
@gregturn This issue should also be now closed, it has been resolved.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-guides/gs-authenticating-ldap/commit/e2bee44edfbaa38434b592e45f12c3f70646f046
