### ISSUE TITLE
Unresolved directive in 'What you’ll need' section of README

### ISSUE THREAD

**Issue by matthew-pearson** [spring-guides/gs-authenticating-ldap#11]
I get this in the rendered readme on the guide's web-page:

	<h2 id="_what_you_ll_need">What you’ll need</h2>
	<div class="sectionbody">
	<div class="paragraph">
	<p>Unresolved directive in &lt;stdin&gt; - include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[] :initial: /initial :complete: /complete</p>
	</div>
	</div>

**Comment by gregturn** [comment]
It must have been a glitch in github at the time of the last commit. It resulted in a cached state of the guide. I refired the same post-commit event, and it regenerated clean copy of the guide.

Thanks for alerting us to it!
