### ISSUE TITLE
Problems with displaying several code snippets on the guide page

### ISSUE THREAD

**Issue by amseager** [spring-guides/gs-authenticating-ldap#25]
Bugs with displaying several code examples on https://spring.io/guides/gs/authenticating-ldap/ (inside "Set up Spring Security" & "Set up user data" paragraphs):

**build.gradle** - Unresolved directive in <stdin> - `include::complete/build.gradle[tag=security,indent=0]`

**pom.xml** - Unresolved directive in <stdin> - `include::complete/pom.xml[tag=security,indent=0]`

**src/main/java/hello/WebSecurityConfig.java** - `Unresolved directive in <stdin> - include::complete/src/main/java/hello/WebSecurityConfig.java[]`

**src/main/resources/test-server.ldif** - `Unresolved directive in <stdin> - include::complete/src/main/resources/test-server.ldif[]`

Btw, Ascii plugin in IDEA shows all of them correctly.

**Comment by dsyer** [comment]
I cleared a cache. Looks OK now.
