### ISSUE TITLE
Link to complete Gradle/Maven config file not working.

### ISSUE THREAD

**Issue by MarkZhangTW** [spring-guides/gs-authenticating-ldap#36]
I don't know how README.adoc reference the content of a link.

It just shows nothing with the following two links:
- `link:complete/build.gradle[]`
- `link:complete/pom.xml[]`

I don't know why so just provides a screenshot for someone knows where the problem is.

![image](https://user-images.githubusercontent.com/16055395/79302616-7745d380-7f1f-11ea-9b80-ec2d0ee0e4a5.png)

**Comment by Buzzardo** [comment]
Fixed in a subsequent commit.
