### ISSUE TITLE
Gradle build failed with error Could not find method implmentation()

### ISSUE THREAD

**Issue by kauser-cse-buet** [spring-guides/gs-authenticating-ldap#52]
Error: 
Could not find method implmentation() for arguments [org.springframework.ldap:spring-ldap-core] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

Any suggestion how can I resolve this?

**Comment by robertmcnees** [comment]
Hi @kauser-cse-buet. Can you give me a bit more information about when you are getting this error? Are you running the build after writing your own code, perhaps starting in the `initial` folder or with a download from Spring Initializr? Are you using the code directly from the `complete` folder? Are you using the gradle wrapper?

Our [CI](https://github.com/spring-guides/gs-authenticating-ldap/actions/workflows/continuous-integration-build.yml) seems to be working fine. I also just pulled down the latest and was able to get a clean build with `./gradlew clean build` in the `complete` directory. 

Let me know when you are getting this error and we can look into it further.

**Comment by robertmcnees** [comment]
Hi @kauser-cse-buet. Have you had the chance to look into this further? I'll leave this issue open for a bit longer but will close it soon if I don't hear back. Let me know if the issue persists.

**Comment by robertmcnees** [comment]
Closing due to lack of response. If this is still an issue, please comment here and we can investigate.
